create table if not exists public.users (
  id bigint generated by default as identity primary key,
  auth_user_id uuid unique,
  email text,
  name varchar(120) not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.fitness_profiles (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  age_range varchar(40),
  gender varchar(40),
  height_cm double precision,
  weight_kg double precision,
  main_goal varchar(80) not null,
  experience_level varchar(40) not null,
  training_location varchar(40) not null,
  available_equipment jsonb not null default '[]'::jsonb,
  weekly_availability integer not null,
  session_length_minutes integer not null,
  preferred_workout_days jsonb not null default '[]'::jsonb,
  injuries_limitations text,
  nutrition_preference varchar(80),
  foods_disliked text,
  allergies text,
  typical_schedule text,
  coaching_style varchar(40) not null default 'direct',
  consent_disclaimer boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id)
);

create table if not exists public.chat_sessions (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  title varchar(160) not null default 'Coach chat',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  session_id bigint not null references public.chat_sessions(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  role varchar(20) not null,
  content text not null,
  metadata_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.workout_plans (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  name varchar(160) not null,
  goal varchar(120) not null,
  duration_weeks integer not null default 4,
  days_per_week integer not null,
  equipment_needed jsonb not null default '[]'::jsonb,
  plan_json jsonb not null default '{}'::jsonb,
  progression_rule text,
  recovery_note text,
  is_current boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.workouts (
  id bigint generated by default as identity primary key,
  plan_id bigint references public.workout_plans(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  name varchar(160) not null,
  scheduled_day varchar(40),
  difficulty varchar(40),
  workout_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.workout_exercises (
  id bigint generated by default as identity primary key,
  workout_id bigint not null references public.workouts(id) on delete cascade,
  name varchar(160) not null,
  sets varchar(40),
  reps_or_duration varchar(80),
  rest varchar(80),
  notes text,
  alternatives jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.workout_logs (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  workout_id bigint references public.workouts(id) on delete set null,
  logged_on date not null,
  status varchar(40) not null,
  exercise_results jsonb not null default '[]'::jsonb,
  rpe integer,
  notes text,
  pain_flag boolean not null default false,
  parse_confidence varchar(20) not null default 'medium',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.meal_logs (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  eaten_on date not null,
  meal_type varchar(40),
  note text,
  image_path varchar(500),
  calories_min integer,
  calories_max integer,
  protein_min integer,
  protein_max integer,
  carbs_min integer,
  carbs_max integer,
  fat_min integer,
  fat_max integer,
  confidence varchar(20),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.meal_items (
  id bigint generated by default as identity primary key,
  meal_id bigint not null references public.meal_logs(id) on delete cascade,
  name varchar(160) not null,
  quantity varchar(120),
  calories_min integer,
  calories_max integer,
  protein_min integer,
  protein_max integer,
  confidence varchar(20),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.meal_image_analyses (
  id bigint generated by default as identity primary key,
  meal_id bigint not null references public.meal_logs(id) on delete cascade,
  detected_items jsonb not null default '[]'::jsonb,
  follow_up_questions jsonb not null default '[]'::jsonb,
  analysis_json jsonb not null default '{}'::jsonb,
  provider_status varchar(40) not null default 'not_configured',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.coaching_memories (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  memory_type varchar(60) not null,
  content text not null,
  source varchar(80) not null default 'chat',
  confidence varchar(20) not null default 'medium',
  is_sensitive boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.memory_summaries (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  summary_type varchar(60) not null default 'long_term',
  content text not null,
  source_range_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.body_metrics (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  measured_on date not null,
  weight_kg double precision,
  waist_cm double precision,
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.weekly_summaries (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  week_start date not null,
  week_end date not null,
  summary_text text not null,
  metrics_json jsonb not null default '{}'::jsonb,
  next_action text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.safety_events (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete cascade,
  event_type varchar(80) not null,
  severity varchar(40) not null,
  source_text text not null,
  response_text text,
  metadata_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.usage_events (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete cascade,
  usage_date date not null,
  task varchar(60) not null,
  provider varchar(60) not null,
  model varchar(120),
  estimated_tokens_in integer not null default 0,
  estimated_tokens_out integer not null default 0,
  token_breakdown_json jsonb not null default '{}'::jsonb,
  cost_estimate double precision,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.pending_actions (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  session_id bigint references public.chat_sessions(id) on delete set null,
  action_type varchar(80) not null,
  status varchar(40) not null default 'pending',
  subject_type varchar(80) not null,
  subject_id bigint not null,
  payload_json jsonb not null default '{}'::jsonb,
  resolution varchar(40),
  created_from_message_id bigint references public.chat_messages(id) on delete set null,
  resolved_by_message_id bigint references public.chat_messages(id) on delete set null,
  resolved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_users_auth_user_id on public.users(auth_user_id);
create index if not exists idx_fitness_profiles_user_id on public.fitness_profiles(user_id);
create index if not exists idx_chat_sessions_user_id on public.chat_sessions(user_id);
create index if not exists idx_chat_messages_user_id on public.chat_messages(user_id);
create index if not exists idx_workout_plans_user_id on public.workout_plans(user_id);
create index if not exists idx_workouts_user_id on public.workouts(user_id);
create index if not exists idx_workout_logs_user_id on public.workout_logs(user_id);
create index if not exists idx_meal_logs_user_id on public.meal_logs(user_id);
create index if not exists idx_coaching_memories_user_id on public.coaching_memories(user_id);
create index if not exists idx_memory_summaries_user_id on public.memory_summaries(user_id);
create index if not exists idx_body_metrics_user_id on public.body_metrics(user_id);
create index if not exists idx_weekly_summaries_user_id on public.weekly_summaries(user_id);
create index if not exists idx_safety_events_user_id on public.safety_events(user_id);
create index if not exists idx_usage_events_user_id on public.usage_events(user_id);
create index if not exists idx_pending_actions_user_id on public.pending_actions(user_id);

grant select, insert, update, delete on
  public.users,
  public.fitness_profiles,
  public.chat_sessions,
  public.chat_messages,
  public.workout_plans,
  public.workouts,
  public.workout_exercises,
  public.workout_logs,
  public.meal_logs,
  public.meal_items,
  public.meal_image_analyses,
  public.coaching_memories,
  public.memory_summaries,
  public.body_metrics,
  public.weekly_summaries,
  public.safety_events,
  public.usage_events,
  public.pending_actions
to authenticated;

grant usage, select on all sequences in schema public to authenticated;

alter table public.users enable row level security;
alter table public.fitness_profiles enable row level security;
alter table public.chat_sessions enable row level security;
alter table public.chat_messages enable row level security;
alter table public.workout_plans enable row level security;
alter table public.workouts enable row level security;
alter table public.workout_exercises enable row level security;
alter table public.workout_logs enable row level security;
alter table public.meal_logs enable row level security;
alter table public.meal_items enable row level security;
alter table public.meal_image_analyses enable row level security;
alter table public.coaching_memories enable row level security;
alter table public.memory_summaries enable row level security;
alter table public.body_metrics enable row level security;
alter table public.weekly_summaries enable row level security;
alter table public.safety_events enable row level security;
alter table public.usage_events enable row level security;
alter table public.pending_actions enable row level security;

drop policy if exists users_own_rows on public.users;
create policy users_own_rows on public.users
for all
to authenticated
using (auth_user_id = (select auth.uid()))
with check (auth_user_id = (select auth.uid()));

drop policy if exists fitness_profiles_own_rows on public.fitness_profiles;
create policy fitness_profiles_own_rows on public.fitness_profiles
for all to authenticated
using (exists (select 1 from public.users where users.id = fitness_profiles.user_id and users.auth_user_id = (select auth.uid())))
with check (exists (select 1 from public.users where users.id = fitness_profiles.user_id and users.auth_user_id = (select auth.uid())));

drop policy if exists chat_sessions_own_rows on public.chat_sessions;
create policy chat_sessions_own_rows on public.chat_sessions
for all to authenticated
using (exists (select 1 from public.users where users.id = chat_sessions.user_id and users.auth_user_id = (select auth.uid())))
with check (exists (select 1 from public.users where users.id = chat_sessions.user_id and users.auth_user_id = (select auth.uid())));

drop policy if exists chat_messages_own_rows on public.chat_messages;
create policy chat_messages_own_rows on public.chat_messages
for all to authenticated
using (exists (select 1 from public.users where users.id = chat_messages.user_id and users.auth_user_id = (select auth.uid())))
with check (exists (select 1 from public.users where users.id = chat_messages.user_id and users.auth_user_id = (select auth.uid())));

drop policy if exists workout_plans_own_rows on public.workout_plans;
create policy workout_plans_own_rows on public.workout_plans
for all to authenticated
using (exists (select 1 from public.users where users.id = workout_plans.user_id and users.auth_user_id = (select auth.uid())))
with check (exists (select 1 from public.users where users.id = workout_plans.user_id and users.auth_user_id = (select auth.uid())));

drop policy if exists workouts_own_rows on public.workouts;
create policy workouts_own_rows on public.workouts
for all to authenticated
using (exists (select 1 from public.users where users.id = workouts.user_id and users.auth_user_id = (select auth.uid())))
with check (exists (select 1 from public.users where users.id = workouts.user_id and users.auth_user_id = (select auth.uid())));

drop policy if exists workout_exercises_own_rows on public.workout_exercises;
create policy workout_exercises_own_rows on public.workout_exercises
for all to authenticated
using (exists (
  select 1 from public.workouts
  join public.users on users.id = workouts.user_id
  where workouts.id = workout_exercises.workout_id and users.auth_user_id = (select auth.uid())
))
with check (exists (
  select 1 from public.workouts
  join public.users on users.id = workouts.user_id
  where workouts.id = workout_exercises.workout_id and users.auth_user_id = (select auth.uid())
));

drop policy if exists workout_logs_own_rows on public.workout_logs;
create policy workout_logs_own_rows on public.workout_logs
for all to authenticated
using (exists (select 1 from public.users where users.id = workout_logs.user_id and users.auth_user_id = (select auth.uid())))
with check (exists (select 1 from public.users where users.id = workout_logs.user_id and users.auth_user_id = (select auth.uid())));

drop policy if exists meal_logs_own_rows on public.meal_logs;
create policy meal_logs_own_rows on public.meal_logs
for all to authenticated
using (exists (select 1 from public.users where users.id = meal_logs.user_id and users.auth_user_id = (select auth.uid())))
with check (exists (select 1 from public.users where users.id = meal_logs.user_id and users.auth_user_id = (select auth.uid())));

drop policy if exists meal_items_own_rows on public.meal_items;
create policy meal_items_own_rows on public.meal_items
for all to authenticated
using (exists (
  select 1 from public.meal_logs
  join public.users on users.id = meal_logs.user_id
  where meal_logs.id = meal_items.meal_id and users.auth_user_id = (select auth.uid())
))
with check (exists (
  select 1 from public.meal_logs
  join public.users on users.id = meal_logs.user_id
  where meal_logs.id = meal_items.meal_id and users.auth_user_id = (select auth.uid())
));

drop policy if exists meal_image_analyses_own_rows on public.meal_image_analyses;
create policy meal_image_analyses_own_rows on public.meal_image_analyses
for all to authenticated
using (exists (
  select 1 from public.meal_logs
  join public.users on users.id = meal_logs.user_id
  where meal_logs.id = meal_image_analyses.meal_id and users.auth_user_id = (select auth.uid())
))
with check (exists (
  select 1 from public.meal_logs
  join public.users on users.id = meal_logs.user_id
  where meal_logs.id = meal_image_analyses.meal_id and users.auth_user_id = (select auth.uid())
));

drop policy if exists coaching_memories_own_rows on public.coaching_memories;
create policy coaching_memories_own_rows on public.coaching_memories
for all to authenticated
using (exists (select 1 from public.users where users.id = coaching_memories.user_id and users.auth_user_id = (select auth.uid())))
with check (exists (select 1 from public.users where users.id = coaching_memories.user_id and users.auth_user_id = (select auth.uid())));

drop policy if exists memory_summaries_own_rows on public.memory_summaries;
create policy memory_summaries_own_rows on public.memory_summaries
for all to authenticated
using (exists (select 1 from public.users where users.id = memory_summaries.user_id and users.auth_user_id = (select auth.uid())))
with check (exists (select 1 from public.users where users.id = memory_summaries.user_id and users.auth_user_id = (select auth.uid())));

drop policy if exists body_metrics_own_rows on public.body_metrics;
create policy body_metrics_own_rows on public.body_metrics
for all to authenticated
using (exists (select 1 from public.users where users.id = body_metrics.user_id and users.auth_user_id = (select auth.uid())))
with check (exists (select 1 from public.users where users.id = body_metrics.user_id and users.auth_user_id = (select auth.uid())));

drop policy if exists weekly_summaries_own_rows on public.weekly_summaries;
create policy weekly_summaries_own_rows on public.weekly_summaries
for all to authenticated
using (exists (select 1 from public.users where users.id = weekly_summaries.user_id and users.auth_user_id = (select auth.uid())))
with check (exists (select 1 from public.users where users.id = weekly_summaries.user_id and users.auth_user_id = (select auth.uid())));

drop policy if exists safety_events_own_rows on public.safety_events;
create policy safety_events_own_rows on public.safety_events
for all to authenticated
using (user_id is null or exists (select 1 from public.users where users.id = safety_events.user_id and users.auth_user_id = (select auth.uid())))
with check (user_id is null or exists (select 1 from public.users where users.id = safety_events.user_id and users.auth_user_id = (select auth.uid())));

drop policy if exists usage_events_own_rows on public.usage_events;
create policy usage_events_own_rows on public.usage_events
for all to authenticated
using (user_id is null or exists (select 1 from public.users where users.id = usage_events.user_id and users.auth_user_id = (select auth.uid())))
with check (user_id is null or exists (select 1 from public.users where users.id = usage_events.user_id and users.auth_user_id = (select auth.uid())));

drop policy if exists pending_actions_own_rows on public.pending_actions;
create policy pending_actions_own_rows on public.pending_actions
for all to authenticated
using (exists (select 1 from public.users where users.id = pending_actions.user_id and users.auth_user_id = (select auth.uid())))
with check (exists (select 1 from public.users where users.id = pending_actions.user_id and users.auth_user_id = (select auth.uid())));

insert into storage.buckets (id, name, public)
values ('meal-images', 'meal-images', false)
on conflict (id) do update set public = excluded.public;

drop policy if exists meal_images_insert_own_folder on storage.objects;
create policy meal_images_insert_own_folder on storage.objects
for insert to authenticated
with check (
  bucket_id = 'meal-images'
  and (storage.foldername(name))[1] = (select auth.uid())::text
);

drop policy if exists meal_images_select_own_folder on storage.objects;
create policy meal_images_select_own_folder on storage.objects
for select to authenticated
using (
  bucket_id = 'meal-images'
  and (storage.foldername(name))[1] = (select auth.uid())::text
);

drop policy if exists meal_images_delete_own_folder on storage.objects;
create policy meal_images_delete_own_folder on storage.objects
for delete to authenticated
using (
  bucket_id = 'meal-images'
  and (storage.foldername(name))[1] = (select auth.uid())::text
);
