-- Phase 1 typed memory facts. This is the single active memory store.
-- No embeddings, vector index, UI state, or consolidation tables are added here.

create table if not exists public.memory_facts (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  type text not null check (
    type in (
      'allergy',
      'medical',
      'injury',
      'restriction_nutrition',
      'equipment',
      'schedule',
      'preference',
      'goal',
      'context_life',
      'pattern_motivation',
      'other'
    )
  ),
  status text not null default 'active' check (status in ('active', 'superseded', 'retracted', 'expired')),
  slot text,
  value_text text,
  text_he text not null,
  confidence text not null default 'medium' check (confidence in ('low', 'medium', 'high')),
  salience double precision not null default 0.5 check (salience >= 0 and salience <= 1),
  source text not null default 'sync_safety',
  source_message_id bigint references public.chat_messages(id) on delete set null,
  safety_event_id bigint references public.safety_events(id) on delete set null,
  valid_at timestamptz,
  invalid_at timestamptz,
  expired_at timestamptz,
  superseded_by bigint references public.memory_facts(id),
  provenance_json jsonb not null default '{}'::jsonb,
  metadata_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_memory_facts_user_type_status on public.memory_facts(user_id, type, status);

create or replace function public.touch_memory_facts() returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_touch_memory_facts on public.memory_facts;
create trigger trg_touch_memory_facts
before update on public.memory_facts
for each row execute function public.touch_memory_facts();

grant select, insert, update, delete on public.memory_facts to authenticated;
grant usage, select on all sequences in schema public to authenticated;

alter table public.memory_facts enable row level security;

drop policy if exists memory_facts_own_rows on public.memory_facts;
create policy memory_facts_own_rows on public.memory_facts
for all to authenticated
using (exists (select 1 from public.users where users.id = memory_facts.user_id and users.auth_user_id = (select auth.uid())))
with check (exists (select 1 from public.users where users.id = memory_facts.user_id and users.auth_user_id = (select auth.uid())));
